version: 2
project_name: sshc

before:
  hooks:
  - go mod tidy

builds:
- id: sshc
  main: ./main.go
  binary: sshc
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X github.com/xvertile/sshc/cmd.AppVersion={{.Version}}
  flags:
  - -trimpath

archives:
- id: sshc
  formats: [ "tar.gz" ]
  format_overrides:
  - goos: windows
    formats: [ "zip" ]
  name_template: >-
    {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
  files:
  - LICENSE
  - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^ci:"
    - "^chore:"

brews:
- name: sshc
  repository:
    owner: xvertile
    name: homebrew-sshc
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/xvertile/sshc"
  description: "A powerful SSH client for the terminal"
  license: MIT
  skip_upload: auto
  test: |
    system "#{bin}/sshc --version"

release:
  github:
    owner: xvertile
    name: sshc
  prerelease: auto
  draft: false
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## SSHC v{{.Version}}

  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install xvertile/sshc/sshc
    ```

    ### Manual
    Download the binary for your platform from assets above.

snapshot:
  version_template: "{{ .Tag }}-snapshot-{{.ShortCommit}}"
